# Scheduled validation of the release binaries
name: cron

on:
  workflow_dispatch:
  pull_request:

jobs:
  release:
    uses: ./.github/workflows/validate-binaries.yml
    with:
      channel: release
      os: all
