# Scheduled validation of the nightly binaries
name: cron

on:
  workflow_dispatch:
  pull_request:

jobs:
  nightly:
    uses: ./.github/workflows/validate-binaries.yml
    with:
      channel: nightly
      os: all
